### PR TITLE
Upstream MBED-TLS integrated SRTP support, use upstream instead

### PR DESCRIPTION
**Pull request by gizahNL**

### CODE REVIEW

**Comment by Thulinma** [comment]
Thanks! We've been wanting this updated for ages but nobody ever had the time to look into what was needed to make it happen.

Just checking - as we haven't yet streamlined this - I assume you're fine with releasing your contribution under the same license as the project? (= public domain)

**Comment by gizahNL** [comment]
> Thanks! We've been wanting this updated for ages but nobody ever had the time to look into what was needed to make it happen.
> 
> Just checking - as we haven't yet streamlined this - I assume you're fine with releasing your contribution under the same license as the project? (= public domain)

Public domain is totally fine. If you need me to sign my commits I can. 

Just an FYI: I didn't get around to testing this yet, besides "it builds" and "looks correct".

For robustness I think the switch statement @ line 276 could do with a case for MBEDTLS_TLS_SRTP_UNSET & error out. And perhaps also a check to verify MKI key len is sufficiently long.

For correctness it's important (according to MBED-TLS docs) that we don't extract/utilize the MKI keying material before the DTLS setup is completed. So that means that DTLSSRTPHandshake::extractKeyingMaterial shouldn't be called before that holds true.

**Comment by Thulinma** [comment]
No need to sign the commits - your agreement here is enough. 👍 Thanks!

Yeah, no worries, I will definitely make sure this gets tested before it is merged.

It looks like mbedtls did not make this easy - the default 2.X branch config seems to not enable DTLS support, and the 3.X branch is not compatible with the current implementation. 🤔
Still, a non-standard compile of the standard code is better than a custom branch, so I'll look into getting this merged ASAP.

**Comment by Thulinma** [comment]
Closing this one in favor of #108, which looks like it also addresses basically all of my concerns. 🥳

**Pull request closed without merging**
